// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBDneDZr3urBzhs7ccUrodmaYkCypT4BQ',
    appId: '1:135150298843:web:8af7efc6f0b0ea5b3f8efe',
    messagingSenderId: '135150298843',
    projectId: 'tabulation-systemv7',
    authDomain: 'tabulation-systemv7.firebaseapp.com',
    storageBucket: 'tabulation-systemv7.firebasestorage.app',
    measurementId: 'G-DCE4S96YJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Yaa7AKXAdmDHwH_nFsGfOwS4KZgllc4',
    appId: '1:135150298843:android:e0e397a2452c811f3f8efe',
    messagingSenderId: '135150298843',
    projectId: 'tabulation-systemv7',
    storageBucket: 'tabulation-systemv7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdjq1LAqdd8UiiwZ-ooTa16oT-pQq0pg',
    appId: '1:135150298843:ios:52d4b49e512fb7283f8efe',
    messagingSenderId: '135150298843',
    projectId: 'tabulation-systemv7',
    storageBucket: 'tabulation-systemv7.firebasestorage.app',
    iosBundleId: 'com.example.tabulationSystemv7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADdjq1LAqdd8UiiwZ-ooTa16oT-pQq0pg',
    appId: '1:135150298843:ios:52d4b49e512fb7283f8efe',
    messagingSenderId: '135150298843',
    projectId: 'tabulation-systemv7',
    storageBucket: 'tabulation-systemv7.firebasestorage.app',
    iosBundleId: 'com.example.tabulationSystemv7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBDneDZr3urBzhs7ccUrodmaYkCypT4BQ',
    appId: '1:135150298843:web:fc8b2a3d3e53fb4f3f8efe',
    messagingSenderId: '135150298843',
    projectId: 'tabulation-systemv7',
    authDomain: 'tabulation-systemv7.firebaseapp.com',
    storageBucket: 'tabulation-systemv7.firebasestorage.app',
    measurementId: 'G-ET1SVTQV90',
  );
}
